### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by syptic** [Ricefrog/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [ ] Commit screenshot for bug/input 2
- [ ] Link to test file for bug/input 2
- [ ] Symptom shown as command + output for bug/input 2
- [ ] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [ ] Commit screenshot for bug/input 3
- [ ] Link to test file for bug/input 3
- [ ] Symptom shown as command + output for bug/input 3
- [ ] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
For full credit try to work on other 2 bug-fixes and then submit a regrade request.
Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Ricefrog** [comment]
The solution my group came up with worked for all but one test file on the first run. I asked my lab group leader if it was okay to just explain the single bug fix and he said it was fine because we only had to fix one bug. For reference my lab group leader is Yasushi Oh.

**Comment by syptic** [comment]
If the solution is fixing multiple bugs then you can try to divide it into different smaller bugs and explain how each code change is fixing one modular bug. For the requirements for this report, you do need 3 bug/input cases so I would suggest trying to either split the current changes or come up with new ones based on your knowledge from the lab. The labs are supposed to help you learn how to find and fix bugs 😄

**Comment by Ricefrog** [comment]
I remembered some older versions of the program we had worked on in Week 3. I added two more bug fixes to my lab report and submitted a regrade request.
